### ISSUE TITLE
Add asynchronous withdrawals

### ISSUE THREAD

**Issue by joaodealmeida** [giftedprimate/scala_opennode#1]
The old withdrawal endpoint (/v1/withdrawals) is deprecated and not recommended for use.

Please use the new Withdrawals endpoint (/v2/withdrawals).
You can find more information on our documentation page.

**Comment by giftedprimate** [comment]
@joaodealmeida got it, I will get this done this weekend. Thanks!

**Comment by giftedprimate** [comment]
@joaodealmeida All done. I also implemented v2 on Mathbot.com with the callback, works great! You guys have built a great api, easily the best BTC api built.
