### ISSUE TITLE
Add account balance endpoint

### ISSUE THREAD

**Issue by joaodealmeida** [giftedprimate/scala_opennode#2]

**Comment by giftedprimate** [comment]
@joaodealmeida Will do, thanks for the input!

**Comment by joaodealmeida** [comment]
I would implement myself if only I understood a it of scala :)

btw, we have new docs at https://developers.opennode.co

**Comment by giftedprimate** [comment]
@joaodealmeida account balance endpoint is added. Just waiting on maven to propagate the new version. I also updated all the Int types to be Long type instead.
